[package]
name = "indb"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
atoi = "0.4.0"

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
