[package]
name = "indb"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
atoi = "0.4.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-futures = "0.2.5"

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
